#!/usr/bin/env python3
import sys
import os

import requests

API_BASE = "https://itch.io/api/1/"
API_KEY = os.getenv("ITCHIO_API_KEY")

# generic utils


def ensure_args(num):
    if num >= len(sys.argv):
        print("not enough arguments (less than %d)" % num, file=sys.stderr)
        exit(1)


# api utils


def errcheck(dic):
    if "errors" in dic and dic['errors']:
        print("API error:", file=sys.stderr)

        for i in dic['errors']:
            print(" - " + i, file=sys.stderr)

        exit(1)


def api_get(*args, **kwargs):
    return requests.get(API_BASE + API_KEY + args[0], *args[1:], **kwargs).json()


def platforms(game):
    if not all(k in game for k in ("p_android", "p_osx", "p_windows", "p_linux")):
        raise Exception("some platforms not found in %s" % game)

    string = "%s%s%s%s" % (
        "A" if game['p_android'] else " ",
        "W" if game['p_windows'] else " ",
        "M" if game['p_osx'] else " ",
        "L" if game['p_linux'] else " ",
    )

    return string


# output things


def print_keys():
    keys = api_get("/my-owned-keys")
    errcheck(keys)
    keys = keys['owned_keys']

    for k in keys:
        print("%s\t%s\t%s\t%s" % (k['id'], k['game_id'], platforms(k['game']), k['game']['title']))


def print_uploads(key):
    ups = api_get("/download-key/%s/uploads" % key)
    errcheck(ups)
    ups = ups['uploads']

    for k in ups:
        print("%s\t%s\t%s\t%s\t%s" % (key, k['id'], platforms(k), k['updated_at'], k['filename']))


def print_dl_links(key, ids):
    for i in ids:
        url = api_get("/download-key/%s/download/%s" % (key, i))
        errcheck(url)
        print(url['url'])


def main():
    if API_KEY is None:
        print("$ITCHIO_API_KEY not set", file=sys.stderr)
        exit(1)

    if sys.argv[1] == "keys":
        print_keys()
    elif sys.argv[1] == "uploads":
        ensure_args(2)
        print_uploads(sys.argv[2])
    elif sys.argv[1] == "dl":
        ensure_args(3)
        print_dl_links(sys.argv[2], sys.argv[3:])
    else:
        print("usage: %s <command> [<args>]" % sys.argv[0], file=sys.stderr)
        print("<command> can be one of the following:", file=sys.stderr)
        print(file=sys.stderr)
        print("  keys    - display keys associated with the account", file=sys.stderr)
        print("    output: key id, game id, platforms, game title", file=sys.stderr)
        print(file=sys.stderr)
        print("  uploads - display uploads associated with the key", file=sys.stderr)
        print("    args: key", file=sys.stderr)
        print("    output: key id, upload id, platforms, last update, game title", file=sys.stderr)
        print(file=sys.stderr)
        print("  dl      - display download links for chosen uploads", file=sys.stderr)
        print("    args: key, upload id...", file=sys.stderr)

if __name__ == "__main__":
    main()
